Works and about me pages set up
yin-ka/Portfolio-setup-and-mobile-first pull request #2
Opened 2023-01-14 18:53 UTC by yin-ka

- Node modules and test.md file ignored
- used flexbox
- export images from Microverse-student-figma file
- external stylesheet used
- html&css linters used
- added .html&.css files

2023-01-14 20:06 UTC, bienvenuushindi requested changes
### Hi @yin-ka ,

Good job implementing most of the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔


## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- [ ] Please check the inline comments below.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-14 20:06 UTC, bienvenuushindi commented on index.html
> +                <img alt="frame" src="Frame 9mj.png" class="">
:red_circle:  Kindly make sure you design this part of the page using HTML and CSS. I am asking myself the following question **Why do we make websites with code instead of just displaying an image of it?** Here are some reasonable answers :arrow_down: 

**User Interactivity.** Maybe they need to request specific data or submit information. Maybe animations happen based on their actions on the site. Maybe users would like to keep information they find on the site in a form that’s more portable than a static image (copy and paste, file download, etc).
**Data. Rarely** is a website just presentation of static information. Oftentimes, that information is dynamic, and must be displayed differently based on various factors, like changes in the data, user experience, user-specific data, etc.
**Responsiveness**. Layout is different based on device and viewport. That can be determined dynamically by code. Even if you wanted your site to consist of static images, you’d still need code to determine which correctly-sized image to display.

These are just few reasons :hugs: 
you have already done the great part of the work. You are almost there be brave :1st_place_medal:

2023-01-18 13:11 UTC, wayungi requested changes
Hi @yin-ka , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![image](https://user-images.githubusercontent.com/99656687/213179747-439aa732-47a3-45a3-973f-88fa88a27982.png)

 ## Highlights
- [ ] Good commit messages 😃 
- [ ] Descriptive PR title 😃 
- [ ] Corrct GitHub flow 😃 
- [ ] Descritive PR body 😃 
- [ ] All linter checks are passing 😃 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 13:11 UTC, wayungi commented on index.html
>                  </div>
- [ ] As the previous reviewer suggested, do not use images in this section. This is supposed to be a drop-down menu. Using images here is non-semantic, and will lead to a loss of functionality and also offset screen readers. Please refer to this [article](https://www.w3schools.com/howto/howto_css_dropdown_navbar.asp) to help you code a drop-down menu

2023-01-19 08:41 UTC, Ibizugbe requested changes
Hi @yin-ka 👋, 

![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d](https://user-images.githubusercontent.com/64643995/213394221-d8b938cc-2b65-4258-9016-57695ca162c1.gif)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅
- github flow has been used👍
- good work implementing the changes requested by the previous reviewers👍

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [OPTIONAL] I think the curves in your intro and about section are not present again, I suggest you add them so your project sticks to the design as it is a requirement🤗
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 08:41 UTC, Ibizugbe commented on index.html
> +        </li>
I see you have put in some effort implementing the changes requested by the previous reviewers👍 As stated by the previous reviewers, I also think using images to highlight a skill is not a good idea, a screen reader will likely misinterpret it.  as used in the design, you can use the language logo and write the name of the language in the text. then use `flex` for the layout😉

2023-01-19 08:41 UTC, Ibizugbe commented on index.html
> +    </section>
[OPTIONAL] Your language section looks a little bit different from the design, I suggest you take a look at the design and make the necessary changes, as it is a requirement that you always stick to the design 👍 

figma
<img width="211" alt="language section figma" src="https://user-images.githubusercontent.com/64643995/213393516-2c0a25fa-2739-445d-bb12-1d5a86b3f40b.png">
yours
<img width="275" alt="language section ur___App" src="https://user-images.githubusercontent.com/64643995/213393625-ca43072e-4904-4963-a6a5-724ff7d30e15.png">

You can notice the drop-down arrows are not properly positioned and the lines are a little bit thicker than the design🤗

2023-01-23 08:59 UTC, merged